### ISSUE TITLE
Layout issues in Boost

### ISSUE THREAD

**Issue by mudrd8mz** [center-for-learning-management/moodle-block_enrolcode#3]
This is how the block appears in the default Boost theme. the arrowed areas are actually clickable and lead to "Invalid code" popup.

![image](https://user-images.githubusercontent.com/85831/74922767-fd3a1800-53cf-11ea-9540-fa05184ab419.png)

**Comment by mudrd8mz** [comment]
Wow, it seems to be even bigger than that. Here are more clickable areas the block seems to create once it is added to the course:

![image](https://user-images.githubusercontent.com/85831/74923351-eba54000-53d0-11ea-93ef-415203e98bdd.png)

**Comment by mudrd8mz** [comment]
I just noticed that this is happening if the page is seen as an admin. When I log in as the teacher, the block appears ok.

**Comment by mudrd8mz** [comment]
Ah, no. I can see it as a student with the block on the Dashboard, too.

**Comment by rschrenk** [comment]
Dear David, thank you for posting this issue. Which version are you using? Are you using the latest one from github, or the one I uploaded to moodle.org  in September? In the meanwhile we have solved some bugs. Kind regards

**Comment by mudrd8mz** [comment]
Hi. We never look into plugins' github repositories. We only look at the officially released code that has been uploaded to the plugins directory - which is the one that most admins would download and install to their sites, too.

**Comment by rschrenk** [comment]
I uploaded our current version, which is from November, into the moodle plugins database. Could you please check again, if that errors are gone? I think we have already solved them a few months ago.

**Comment by mudrd8mz** [comment]
Yes! Those grey areas are now gone in the latest released version. Thanks!
