### ISSUE TITLE
Better describe the actual functionality

### ISSUE THREAD

**Issue by mudrd8mz** [center-for-learning-management/moodle-block_enrolcode#4]
The plugin description at https://moodle.org/plugins/block_enrolcode should be improved to better describe how the block actually works, that is uses the first found manual enrolment instance (or creates a new one), that the code has a default expiration period etc.

I had to discover all these aspects of the behaviour only from reading the code.

**Comment by rschrenk** [comment]
improved readme in 6f007590496f776fae5d913b85cfc1a25e983a95
