### ISSUE TITLE
Terminology: Custom Maturity

### ISSUE THREAD

**Issue by mudrd8mz** [center-for-learning-management/moodle-block_enrolcode#5]
It may be just me, but I had to check the code to better understand what the term "custom maturity" means in this plugin. Maybe something like "expiration period" or "valid until" or something like that might be more clear.

Not a real problem, just a feedback :-)

**Comment by mudrd8mz** [comment]
BTW, the English language pack in Moodle does not use capitalised titles. So it should read "Custom maturity".

**Comment by rschrenk** [comment]
Done in 082e4f0ed39ba38ad4d272fe119e4d4558821188

**Comment by rschrenk** [comment]
Done in 082e4f0ed39ba38ad4d272fe119e4d4558821188
